package Vistas;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

public class FRMInicioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRMInicioPrincipal
     */
    public FRMInicioPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNPrincipal = new javax.swing.JDesktopPane();
        pnlPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnAbrirFoto = new javax.swing.JMenuItem();
        BtnCerrarFoto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout BTNPrincipalLayout = new javax.swing.GroupLayout(BTNPrincipal);
        BTNPrincipal.setLayout(BTNPrincipalLayout);
        BTNPrincipalLayout.setHorizontalGroup(
            BTNPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        BTNPrincipalLayout.setVerticalGroup(
            BTNPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        jMenu1.setText("Fotos");

        BtnAbrirFoto.setText("AbrirFoto");
        BtnAbrirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirFotoActionPerformed(evt);
            }
        });
        jMenu1.add(BtnAbrirFoto);

        BtnCerrarFoto.setText("CerrarFoto");
        BtnCerrarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarFotoActionPerformed(evt);
            }
        });
        jMenu1.add(BtnCerrarFoto);

        pnlPrincipal.add(jMenu1);

        setJMenuBar(pnlPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarFotoActionPerformed
    
        FRMFoto frm = new FRMFoto();
        
        frm.setMaximizable(true);
        frm.setClosable(true);
        frm.setResizable(true);
        frm.setTitle("Nueva foto");
        pnlPrincipal.add(frm);   
        frm.setVisible(true);
        
    }//GEN-LAST:event_BtnCerrarFotoActionPerformed

    private void BtnAbrirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirFotoActionPerformed
        // TODO add your handling code here:
        int respuesta;
        String ruta;
        JFileChooser VentanaArchivos = new JFileChooser();
        respuesta = VentanaArchivos.showOpenDialog(this); //venta para abrir archivos
           
        if (respuesta==JFileChooser.APPROVE_OPTION){
    
        FRMFoto frm = new FRMFoto();
        
        frm.setMaximizable(true);
        frm.setClosable(true);
        frm.setResizable(true);
        pnlPrincipal.add(frm); 
        ruta = VentanaArchivos.getSelectedFile().toString();
        
        frm.setTitle(ruta);
        frm.SetFoto(ruta);
        frm.setVisible(true);
        
        
         }
    }//GEN-LAST:event_BtnAbrirFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMInicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMInicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMInicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMInicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMInicioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane BTNPrincipal;
    private javax.swing.JMenuItem BtnAbrirFoto;
    private javax.swing.JMenuItem BtnCerrarFoto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
