/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Entidades.Productos;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class formProducto extends javax.swing.JFrame {
    //creamos la lista
    DefaultListModel modelo;
    //creamos el array de producto para guardar los productos nuevos y poder odernarlos
    Productos ProductosArray[];
    
    ButtonGroup grupoOrdenamiento;
    
    /**
     * Creates new form FormProducto
     */
    public formProducto() {
        initComponents();
        //instanciamos el array
        this.ProductosArray=new Productos[10];
        //instanciamos el objeto aca para poder usarlo en cualquier lado.
        this.modelo=new DefaultListModel();
        //seteamos el modelo
        this.lstProductos.setModel(modelo);
        //instanciamos
        grupoOrdenamiento=new ButtonGroup();
        //agregamos los botonoes radio buttons de nombre y de precio
        grupoOrdenamiento.add(this.rdoOrdenPrecioAsc);
        grupoOrdenamiento.add(this.rdoOrdenNombreAsc);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList<>();
        txtPrecio = new javax.swing.JTextField();
        rdoOrdenNombreAsc = new javax.swing.JRadioButton();
        rdoOrdenPrecioAsc = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lstProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProductos);

        rdoOrdenNombreAsc.setText("Ordenar por nombre");

        rdoOrdenPrecioAsc.setText("Ordenar por precio");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton1.setText("Igualar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(27, 27, 27))
                                .addComponent(jLabel2)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoOrdenNombreAsc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdoOrdenPrecioAsc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoOrdenNombreAsc)
                        .addGap(82, 82, 82)
                        .addComponent(rdoOrdenPrecioAsc))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jButton1))
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre;
        String  precio;
        
        precio=this.txtPrecio.getText();
        nombre=this.txtNombre.getText();
        
        if(precio.equalsIgnoreCase("") || nombre.equalsIgnoreCase(""))
        {   
            //this.MostrarAlerta();
            
            JOptionPane.showMessageDialog(this, "Faltan datos", "todos los datos deben estar completos", JOptionPane.ERROR_MESSAGE);
        }else
        {   //creamos un producto y lo instaciamos
            Productos unProducto=new Productos(nombre, precio);
            //creamos la variable indiceLibre para poder usarla como indice en el array de produtco
            //int indiceLibre=this.RetornarPrimerLugarLibre(ProductosArray);
            
            //lo guardamos en el array
            //this.ProductosArray[indiceLibre]=unProducto;
            
            
            if(this.CargarProducto(unProducto)==true)
            {
                //lo cargamos en el modelo enviandole el array
                this.CargarModelo(ProductosArray);
                //this.modelo.addElement(unProducto.mostrarProducto());
                this.txtNombre.setText("");
                this.txtPrecio.setText("");
            }else
            {
               JOptionPane.showMessageDialog(this, "Esta lleno", "no hay mas lugar", JOptionPane.ERROR_MESSAGE); 
            }
                
            
            
        }
        
        //this.txtNombre.setText(nombre);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void igualarListado (){
    
    this.lstProductos.setModel(modelo);
         
    }
    
    private boolean CargarProducto(Productos aux)
    {
        boolean retorno=false;
        
        int indiceLibre=this.RetornarPrimerLugarLibre(ProductosArray);
        
        if(indiceLibre!=-1)
        {
           this.ProductosArray[indiceLibre]=aux; 
           retorno=true;
        }
        
        return retorno;
    }
    private int RetornarPrimerLugarLibre(Productos[] arrayProd)
    {   
        int i;
        
        for (i = 0; i < arrayProd.length; i++) {
            //si el array es igual a nulo devolvemos ese lugar ya que seria libre
            if(arrayProd[i]==null)
            {
                break;
            }
            if(i==arrayProd.length)
            {
                i=-1;
            }
        }
        
        return i;
    }
    
    private void CargarModelo(Productos[] arrayProd)
    {   this.modelo.clear();
        //System.out.println("largo" +arrayProd.length);
        //System.out.println("indice "+this.RetornarPrimerLugarLibre(arrayProd));
        //recorre el array y por cada producto que tiene lo agregar al modelo
        for (int i = 0; i < arrayProd.length; i++) {
            //si el array es diferente a nulo lo agrega al modelo
            if(arrayProd[i]!=null)
            {
                this.modelo.addElement(arrayProd[i].mostrarProducto());
            }
            
        }
    }
    private void MostrarAlerta()
    {
            //para crear una entana emergente
            JDialog ventana=new JDialog();
            //para que la ventana no se esconda
            ventana.setAlwaysOnTop(true);
            //para ponerle titulo a la ventana emergente
            ventana.setTitle("Faltan datos");
            //para ponerle el tama�o a la ventana emergente(ancho, alto)
            ventana.setSize(150, 100);
            
            ventana.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            //es para no ir al otro formulario, osea espera si o si una accion.
            ventana.setModal(true);
            ventana.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstProductos;
    private javax.swing.JRadioButton rdoOrdenNombreAsc;
    private javax.swing.JRadioButton rdoOrdenPrecioAsc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}